---
name: Checks
 
on: [push]
 
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.MY_DOCKER_USERNAME }} # Ensure this secret exists in your repository settings
          password: ${{ secrets.MY_DOCKERHUB_TOKEN }} # Ensure this secret exists in your repository settings, or create it in GitHub > Settings > Secrets and variables > Actions
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"